### ISSUE TITLE
Check newest filesideload against released CSVImporter

### ISSUE THREAD

**Issue by patrickmj** [omeka-s-modules/FileSideload#11]
We've redone FileSideload to work with the actually released version of CSVImport. So, a quick test against those is in order.

Master of FileSideload and CSVImport, and develop of Omeka S core.

**Comment by mebrett** [comment]
Remind me what reference the CSV needs for sideload - just the file name?

**Comment by patrickmj** [comment]
Yep, with whatever column header you want to map. This is an example of what I've been using

```
title, sideload
allStatus, allStatus.png
babyLLama, babyLLama.jpg

```

The directory is in the sideload configuration.

**Comment by mebrett** [comment]
It worked fine for me. Imported image and audio file, no problem.
