### ISSUE TITLE
Cannot store files with the resolved extension \"html\"."

### ISSUE THREAD

**Issue by pprw** [omeka-s-modules/FileSideload#18]
I use sideload with csv import and obtain this error:

 "Error validating \"file.html\". Cannot store files with the resolved extension \"html\"."

Any idea? Permissions seems to be ok in the server side.

**Comment by zerocrates** [comment]
This is just saying that "html" isn't in your list of allowed extensions.

**Comment by pprw** [comment]
Ok thanks I managed to fix this message.
