### ISSUE TITLE
Batch Add

### ISSUE THREAD

**Issue by rcampoamor** [omeka-s-modules/FileSideload#22]
The description of this module makes reference to batch adding " It will allow users to batch-add many files at once to their repository, rather than uploading the files individually."  But the actual usage directions describe loading a single file at a time -- which is correct?

**Comment by sharonmleon** [comment]
The module allows you to upload as many files as you want directly to a folder on your server, using whatever transfer utility you would like. It is designed to be in lieu of using the upload capacity within the admin interface for the core software, which limits the process of uploading to a single file at a time and can be subject to file size caps determined by the server settings.
