### ISSUE TITLE
Version 1.6.0 does not appear on omeka.org

### ISSUE THREAD

**Issue by jajm** [omeka-s-modules/FileSideload#28]
There is a 1.6.0 release on github but it does not show up on omeka.org:

![image](https://user-images.githubusercontent.com/306836/192954948-05cd5b11-84b4-4d59-aca7-1516aacf8d54.png)

I guess this is because of the asset name ("Filesideload-1.6.0.zip" vs the expected "FileSideload-1.6.0.zip")

**Comment by jimsafley** [comment]
Thanks. It should be published by tomorrow morning. In the meantime it's available [here](https://github.com/omeka-s-modules/FileSideload/releases/tag/v1.6.1).
