### ISSUE TITLE
Error: invalid omeka_version_constraint

### ISSUE THREAD

**Issue by hlj2014** [omeka-s-modules/FileSideload#3]
Hello,

Excited to try out this module with Omeka S. I've just installed Omeka S 1.0.0 beta and attempted to install FileSideload 1.0.0 alpha but am receiving this error in the Omeka S Dashboard in place of an Install button: "Error: invalid omeka_version_constraint." Took a quick look around but not sure where I've gone wrong. Any clue what might be going on? 

Thanks!

Hannah

**Comment by zerocrates** [comment]
The reason you're seeing that error is that the current version of FileSideload requires a newer version of Omeka S. The "official" preview release of FileSideload will come alongside the version of S that it requires (1.0.0-beta2).

If you want to try it out now, you'll have to also check out the current version of S from Github.

**Comment by zerocrates** [comment]
One question: does it _just_ say "invalid omeka_version_constraint"? It should also be showing you the constraint (i.e., what version is required).

**Comment by hlj2014** [comment]
Hi, As far as I know I have the most recent version of Omeka S available--where might I find 1.0.0-beta2?

Yes, it says only "invalid omeka_version_constraint". No version is given. 

Thanks!

**Comment by hlj2014** [comment]
Ok, thanks. I was chomping at the bit. :)
