### ISSUE TITLE
Documentation: Updates for Omeka S 4.0

### ISSUE THREAD

**Issue by jimsafley** [omeka-s-modules/FileSideload#30]
Per #27, we should recommend that users turn off File Sideload's automatic deletion when performing batch create/update operations. Otherwise, should an error occur during the operation, the module may delete the files before the corresponding items are created.

**Comment by allanaaa** [comment]
This isn't a 4.0 change, right? I can push this immediately?

**Comment by jimsafley** [comment]
Yeah, sorry, this is not specific to 4.0.
