### ISSUE TITLE
File is ingested even if copy to temporary directory fails

### ISSUE THREAD

**Issue by jajm** [omeka-s-modules/FileSideload#36]
https://github.com/omeka-s-modules/FileSideload/blob/f6bf93056bbc58f1e7672372d7a5418b9216a7c7/src/Media/Ingester/Sideload.php#L113

Return value is not checked so the ingestion process continue even if the copy failed.

Happened to me with a big file. There was not enough space left in /tmp so Omeka ingested a truncated version of the file.
I think the same problem exists with SideloadDir

To reproduce:
1. Create a 2M temporary fs: `sudo mount -t tmpfs -o size=2M tmpfs ~/tmp`
2. Change temp_dir to `~/tmp` in local.config.php
3. Try to ingest a file bigger than 2M

**Comment by jimsafley** [comment]
Thanks for the bug report!

**Comment by jajm** [comment]
Thank you for fixing it! :-)
