### ISSUE TITLE
How to trigger Sideload? 

### ISSUE THREAD

**Issue by n3rve** [omeka-s-modules/FileSideload#6]
Hi, I've setup this module on an Omeka-S instance and setup the directory and access rights to the www-data (user Omeka is being run as). After uploading a sample PDF to the configured uploads directory, it's not being added as an item. Is there a way to trigger the sideload, perhaps via a cron job or similar?

**Comment by n3rve** [comment]
I found it in the $omeka-s/admin/item/add#item-media directory, I was hoping this will allow bulk import of thousands of media (PDFs). Is this possible, or planned?

**Comment by patrickmj** [comment]
CSVImport might work directly, if you can put the files into a web-accessible location. It also integrates with FileSideload, so you can use it that way, too. You'd just need to set up the CSV file with metadata and the filenames.
